version: '3.5'
services:
  postgres:
    restart: always
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Qwertyu10P
    networks:
      - service-network
  usermanagement:
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./
      ports:
        - '80:8080'
      environment:
        - MS_HTTP=8080
        - MS_POSTGRES_HOST=postgres
        - MS_POSTGRES_PORT=5432
        - MS_POSTGRES_DBNAME=postgres
        - MS_POSTGRES_USERNAME=postgres
        - MS_POSTGRES_PASSWORD=Qwertyu10P
      networks:
        - service-network
volumes:
  postgres-data:
networks:
  service-network:
   name: service-network